import React, { useState } from 'react'
import { Cpu, AlertTriangle } from 'lucide-react'
import { SectionHeader, StatusBadge, LoadingState, ErrorState, EmptyState } from './Shared.jsx'

export default function GraniteDiagnosticsView({ assets, loadingData, dataError, onRefresh, authHeader }) {
  const [selectedAsset, setSelectedAsset] = useState(assets[0]?.asset_code || '')
  const [explanation, setExplanation] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [mode, setMode] = useState(null) // 'live' | 'offline'

  if (loadingData) return <LoadingState />
  if (dataError && !assets.length) return <ErrorState message={dataError} onRetry={onRefresh} />

  const handleGenerate = async () => {
    if (!selectedAsset) return
    setLoading(true)
    setError(null)
    setExplanation(null)
    setMode(null)
    try {
      const res = await fetch(`/api/v1/copilot/explain/${selectedAsset}`, { headers: authHeader })
      if (!res.ok) {
        const err = await res.json().catch(() => ({}))
        throw new Error(err.detail || `Request failed: ${res.status}`)
      }
      const data = await res.json()
      setExplanation(data.explanation || data.detail || 'No explanation returned from Granite service.')
      // Heuristic: offline mode usually contains "offline" or "deterministic"
      setMode(data.watsonx_mode || (data.explanation?.toLowerCase().includes('offline') ? 'offline' : 'live'))
    } catch (e) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <SectionHeader
        tag="IBM watsonx.ai · Granite 3-8B Instruct"
        label="Natural Language Diagnostic Intelligence"
        desc="Root-cause explanations for readiness degradation generated by IBM Granite 3-8B Instruct. Live watsonx.ai call when IBM Cloud credentials are present; offline deterministic fallback otherwise — mode is labeled below."
      />

      {/* Known limitations box */}
      <div style={{ padding: '12px 16px', background: 'rgba(245,158,11,0.06)', border: '1px solid rgba(245,158,11,0.3)', display: 'flex', gap: 10 }}>
        <AlertTriangle size={14} color="#F59E0B" style={{ flexShrink: 0, marginTop: 1 }} />
        <p style={{ fontSize: 11, color: '#F59E0B', margin: 0, lineHeight: 1.6 }}>
          <strong>SYSTEM STATUS:</strong> If no IBM Cloud credentials are configured (WATSONX_API_KEY + WATSONX_PROJECT_ID in .env), the system uses an offline deterministic Granite 3-8B simulation engine — all responses are clearly labeled with their source mode.
        </p>
      </div>

      {/* Controls */}
      <div className="panel" style={{ padding: '20px 24px' }}>
        <p className="label-upper" style={{ marginBottom: 16 }}>SELECT PLATFORM FOR DIAGNOSTIC</p>

        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10, alignItems: 'flex-end' }}>
          <div style={{ flex: '1 1 280px' }}>
            <p style={{ fontSize: 10, color: '#7D7D7D', textTransform: 'uppercase', letterSpacing: '0.1em', fontFamily: 'JetBrains Mono, monospace', marginBottom: 8 }}>TARGET AIRFRAME</p>
            <select className="select-dark" value={selectedAsset} onChange={e => { setSelectedAsset(e.target.value); setExplanation(null); setError(null) }}>
              {assets.map(a => (
                <option key={a.id} value={a.asset_code}>{a.asset_code} — {a.name} ({a.status} · {a.readiness_score}%)</option>
              ))}
            </select>
          </div>
          <button className="btn-gold" onClick={handleGenerate} disabled={loading || !selectedAsset} style={{ minWidth: 240 }}>
            <Cpu size={15} />
            {loading ? 'QUERYING GRANITE 3-8B...' : 'GENERATE DIAGNOSTIC REPORT'}
          </button>
        </div>
      </div>

      {/* Loading */}
      {loading && (
        <div className="panel" style={{ padding: '40px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12 }}>
          <div className="spinner" />
          <p style={{ fontSize: 11, color: '#7D7D7D', fontFamily: 'JetBrains Mono, monospace', textAlign: 'center' }}>
            QUERYING IBM WATSONX.AI GRANITE 3-8B INSTRUCT...
          </p>
          <p style={{ fontSize: 10, color: '#494949', textAlign: 'center' }}>
            Analyzing HUMS telemetry, C-MAPSS RUL excursions, and component degradation history
          </p>
        </div>
      )}

      {/* Error */}
      {error && !loading && (
        <div style={{ padding: '16px', background: 'rgba(239,68,68,0.06)', border: '1px solid rgba(239,68,68,0.3)' }}>
          <p style={{ fontSize: 12, fontWeight: 700, color: '#EF4444', margin: 0, marginBottom: 4 }}>⚠ DIAGNOSTIC REQUEST FAILED</p>
          <p style={{ fontSize: 11, color: '#7D7D7D', margin: 0 }}>{error}</p>
          <p style={{ fontSize: 10, color: '#494949', margin: 0, marginTop: 4 }}>
            Ensure the FastAPI backend is running and watsonx.ai or offline fallback is configured.
          </p>
        </div>
      )}

      {/* Explanation output */}
      {explanation && !loading && (
        <div className="panel" style={{ padding: '24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16, paddingBottom: 12, borderBottom: '1px solid #494949', flexWrap: 'wrap', gap: 8 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <Cpu size={16} color="#A855F7" />
              <p style={{ fontSize: 12, fontWeight: 700, color: '#A855F7', textTransform: 'uppercase', letterSpacing: '0.06em', margin: 0 }}>
                GRANITE 3-8B DIAGNOSTIC REPORT
              </p>
            </div>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
              <span style={{ fontSize: 10, fontFamily: 'JetBrains Mono, monospace', fontWeight: 700, color: '#FFC000' }}>{selectedAsset}</span>
              {mode && (
                <span style={{
                  fontSize: 10, fontFamily: 'JetBrains Mono, monospace', fontWeight: 700,
                  padding: '2px 8px',
                  background: mode === 'live' ? 'rgba(34,197,94,0.12)' : 'rgba(245,158,11,0.12)',
                  border: `1px solid ${mode === 'live' ? '#22C55E40' : '#F59E0B40'}`,
                  color: mode === 'live' ? '#22C55E' : '#F59E0B',
                }}>
                  {mode === 'live' ? '● LIVE watsonx.ai' : '○ OFFLINE SIMULATION'}
                </span>
              )}
            </div>
          </div>
          <p style={{ fontSize: 13, color: '#F5F5F5', lineHeight: 1.8, whiteSpace: 'pre-wrap', margin: 0 }}>
            {explanation}
          </p>
        </div>
      )}

      {/* Empty initial state */}
      {!explanation && !loading && !error && (
        <div style={{ padding: '60px 24px', textAlign: 'center', border: '1px solid #2A2A2A', background: '#181818' }}>
          <Cpu size={32} color="#494949" style={{ margin: '0 auto 12px' }} />
          <p style={{ fontSize: 12, fontWeight: 700, color: '#7D7D7D', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 }}>
            GRANITE DIAGNOSTIC READY
          </p>
          <p style={{ fontSize: 11, color: '#494949' }}>
            Select a platform and click "Generate Diagnostic Report" to query IBM Granite 3-8B Instruct for a natural-language root-cause analysis.
          </p>
        </div>
      )}
    </div>
  )
}
